// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ipc/gatewayGrpc/gateway.proto

package gatewayGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gateway -> orchestrator (wrapper)
type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Register
	//	*GatewayMessage_Heartbeat
	//	*GatewayMessage_Status
	//	*GatewayMessage_Pong
	//	*GatewayMessage_ShutdownAck
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *GatewayMessage) GetStatus() *StatusReport {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *GatewayMessage) GetPong() *PingResponse {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *GatewayMessage) GetShutdownAck() *ShutdownAck {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_ShutdownAck); ok {
			return x.ShutdownAck
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type GatewayMessage_Status struct {
	Status *StatusReport `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type GatewayMessage_Pong struct {
	Pong *PingResponse `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type GatewayMessage_ShutdownAck struct {
	ShutdownAck *ShutdownAck `protobuf:"bytes,5,opt,name=shutdown_ack,json=shutdownAck,proto3,oneof"`
}

func (*GatewayMessage_Register) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

func (*GatewayMessage_Status) isGatewayMessage_Payload() {}

func (*GatewayMessage_Pong) isGatewayMessage_Payload() {}

func (*GatewayMessage_ShutdownAck) isGatewayMessage_Payload() {}

// orchestrator -> gateway (wrapper)
type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OrchestratorMessage_RegisterResponse
	//	*OrchestratorMessage_HeartbeatAck
	//	*OrchestratorMessage_Ping
	//	*OrchestratorMessage_Shutdown
	Payload       isOrchestratorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *OrchestratorMessage) GetPayload() isOrchestratorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrchestratorMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Payload.(*OrchestratorMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isOrchestratorMessage_Payload interface {
	isOrchestratorMessage_Payload()
}

type OrchestratorMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type OrchestratorMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type OrchestratorMessage_Ping struct {
	Ping *PingRequest `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type OrchestratorMessage_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,4,opt,name=shutdown,proto3,oneof"`
}

func (*OrchestratorMessage_RegisterResponse) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_HeartbeatAck) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_Ping) isOrchestratorMessage_Payload() {}

func (*OrchestratorMessage_Shutdown) isOrchestratorMessage_Payload() {}

// gateway -> orchestrator: initial registration
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *RegisterRequest) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// gateway -> orchestrator: periodic health signal
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShareToken        string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	ToolInvocations   int64                  `protobuf:"varint,3,opt,name=tool_invocations,json=toolInvocations,proto3" json:"tool_invocations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HeartbeatRequest) GetToolInvocations() int64 {
	if x != nil {
		return x.ToolInvocations
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{5}
}

// gateway -> orchestrator: state change notification
type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "starting", "running", "stopping", "failed"
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *StatusReport) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *StatusReport) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// orchestrator -> gateway: health check
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{7}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// orchestrator -> gateway: shutdown command
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShutdownAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownAck) Reset() {
	*x = ShutdownAck{}
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAck) ProtoMessage() {}

func (x *ShutdownAck) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_gatewayGrpc_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAck.ProtoReflect.Descriptor instead.
func (*ShutdownAck) Descriptor() ([]byte, []int) {
	return file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ShutdownAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_ipc_gatewayGrpc_gateway_proto protoreflect.FileDescriptor

const file_ipc_gatewayGrpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dipc/gatewayGrpc/gateway.proto\"\xff\x01\n" +
	"\x0eGatewayMessage\x12.\n" +
	"\bregister\x18\x01 \x01(\v2\x10.RegisterRequestH\x00R\bregister\x121\n" +
	"\theartbeat\x18\x02 \x01(\v2\x11.HeartbeatRequestH\x00R\theartbeat\x12'\n" +
	"\x06status\x18\x03 \x01(\v2\r.StatusReportH\x00R\x06status\x12#\n" +
	"\x04pong\x18\x04 \x01(\v2\r.PingResponseH\x00R\x04pong\x121\n" +
	"\fshutdown_ack\x18\x05 \x01(\v2\f.ShutdownAckH\x00R\vshutdownAckB\t\n" +
	"\apayload\"\xec\x01\n" +
	"\x13OrchestratorMessage\x12@\n" +
	"\x11register_response\x18\x01 \x01(\v2\x11.RegisterResponseH\x00R\x10registerResponse\x124\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\r.HeartbeatAckH\x00R\fheartbeatAck\x12\"\n" +
	"\x04ping\x18\x03 \x01(\v2\f.PingRequestH\x00R\x04ping\x12.\n" +
	"\bshutdown\x18\x04 \x01(\v2\x10.ShutdownRequestH\x00R\bshutdownB\t\n" +
	"\apayload\"D\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\"D\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10tool_invocations\x18\x03 \x01(\x03R\x0ftoolInvocations\"\x0e\n" +
	"\fHeartbeatAck\"[\n" +
	"\fStatusReport\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\")\n" +
	"\x0fShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\")\n" +
	"\vShutdownAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2B\n" +
	"\n" +
	"GatewayIPC\x124\n" +
	"\aConnect\x12\x0f.GatewayMessage\x1a\x14.OrchestratorMessage(\x010\x01B1Z/github.com/hanzozt/mcp-gateway/ipc/gatewayGrpcb\x06proto3"

var (
	file_ipc_gatewayGrpc_gateway_proto_rawDescOnce sync.Once
	file_ipc_gatewayGrpc_gateway_proto_rawDescData []byte
)

func file_ipc_gatewayGrpc_gateway_proto_rawDescGZIP() []byte {
	file_ipc_gatewayGrpc_gateway_proto_rawDescOnce.Do(func() {
		file_ipc_gatewayGrpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_gatewayGrpc_gateway_proto_rawDesc), len(file_ipc_gatewayGrpc_gateway_proto_rawDesc)))
	})
	return file_ipc_gatewayGrpc_gateway_proto_rawDescData
}

var file_ipc_gatewayGrpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ipc_gatewayGrpc_gateway_proto_goTypes = []any{
	(*GatewayMessage)(nil),      // 0: GatewayMessage
	(*OrchestratorMessage)(nil), // 1: OrchestratorMessage
	(*RegisterRequest)(nil),     // 2: RegisterRequest
	(*RegisterResponse)(nil),    // 3: RegisterResponse
	(*HeartbeatRequest)(nil),    // 4: HeartbeatRequest
	(*HeartbeatAck)(nil),        // 5: HeartbeatAck
	(*StatusReport)(nil),        // 6: StatusReport
	(*PingRequest)(nil),         // 7: PingRequest
	(*PingResponse)(nil),        // 8: PingResponse
	(*ShutdownRequest)(nil),     // 9: ShutdownRequest
	(*ShutdownAck)(nil),         // 10: ShutdownAck
}
var file_ipc_gatewayGrpc_gateway_proto_depIdxs = []int32{
	2,  // 0: GatewayMessage.register:type_name -> RegisterRequest
	4,  // 1: GatewayMessage.heartbeat:type_name -> HeartbeatRequest
	6,  // 2: GatewayMessage.status:type_name -> StatusReport
	8,  // 3: GatewayMessage.pong:type_name -> PingResponse
	10, // 4: GatewayMessage.shutdown_ack:type_name -> ShutdownAck
	3,  // 5: OrchestratorMessage.register_response:type_name -> RegisterResponse
	5,  // 6: OrchestratorMessage.heartbeat_ack:type_name -> HeartbeatAck
	7,  // 7: OrchestratorMessage.ping:type_name -> PingRequest
	9,  // 8: OrchestratorMessage.shutdown:type_name -> ShutdownRequest
	0,  // 9: GatewayIPC.Connect:input_type -> GatewayMessage
	1,  // 10: GatewayIPC.Connect:output_type -> OrchestratorMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ipc_gatewayGrpc_gateway_proto_init() }
func file_ipc_gatewayGrpc_gateway_proto_init() {
	if File_ipc_gatewayGrpc_gateway_proto != nil {
		return
	}
	file_ipc_gatewayGrpc_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*GatewayMessage_Register)(nil),
		(*GatewayMessage_Heartbeat)(nil),
		(*GatewayMessage_Status)(nil),
		(*GatewayMessage_Pong)(nil),
		(*GatewayMessage_ShutdownAck)(nil),
	}
	file_ipc_gatewayGrpc_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*OrchestratorMessage_RegisterResponse)(nil),
		(*OrchestratorMessage_HeartbeatAck)(nil),
		(*OrchestratorMessage_Ping)(nil),
		(*OrchestratorMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_gatewayGrpc_gateway_proto_rawDesc), len(file_ipc_gatewayGrpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipc_gatewayGrpc_gateway_proto_goTypes,
		DependencyIndexes: file_ipc_gatewayGrpc_gateway_proto_depIdxs,
		MessageInfos:      file_ipc_gatewayGrpc_gateway_proto_msgTypes,
	}.Build()
	File_ipc_gatewayGrpc_gateway_proto = out.File
	file_ipc_gatewayGrpc_gateway_proto_goTypes = nil
	file_ipc_gatewayGrpc_gateway_proto_depIdxs = nil
}
