// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: ipc/gatewayGrpc/gateway.proto

package gatewayGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayIPC_Connect_FullMethodName = "/GatewayIPC/Connect"
)

// GatewayIPCClient is the client API for GatewayIPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayIPCClient interface {
	// bidirectional stream: gateway connects, both sides send messages
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayMessage, OrchestratorMessage], error)
}

type gatewayIPCClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayIPCClient(cc grpc.ClientConnInterface) GatewayIPCClient {
	return &gatewayIPCClient{cc}
}

func (c *gatewayIPCClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayMessage, OrchestratorMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayIPC_ServiceDesc.Streams[0], GatewayIPC_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewayMessage, OrchestratorMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayIPC_ConnectClient = grpc.BidiStreamingClient[GatewayMessage, OrchestratorMessage]

// GatewayIPCServer is the server API for GatewayIPC service.
// All implementations must embed UnimplementedGatewayIPCServer
// for forward compatibility.
type GatewayIPCServer interface {
	// bidirectional stream: gateway connects, both sides send messages
	Connect(grpc.BidiStreamingServer[GatewayMessage, OrchestratorMessage]) error
	mustEmbedUnimplementedGatewayIPCServer()
}

// UnimplementedGatewayIPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayIPCServer struct{}

func (UnimplementedGatewayIPCServer) Connect(grpc.BidiStreamingServer[GatewayMessage, OrchestratorMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGatewayIPCServer) mustEmbedUnimplementedGatewayIPCServer() {}
func (UnimplementedGatewayIPCServer) testEmbeddedByValue()                    {}

// UnsafeGatewayIPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayIPCServer will
// result in compilation errors.
type UnsafeGatewayIPCServer interface {
	mustEmbedUnimplementedGatewayIPCServer()
}

func RegisterGatewayIPCServer(s grpc.ServiceRegistrar, srv GatewayIPCServer) {
	// If the following call panics, it indicates UnimplementedGatewayIPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayIPC_ServiceDesc, srv)
}

func _GatewayIPC_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayIPCServer).Connect(&grpc.GenericServerStream[GatewayMessage, OrchestratorMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayIPC_ConnectServer = grpc.BidiStreamingServer[GatewayMessage, OrchestratorMessage]

// GatewayIPC_ServiceDesc is the grpc.ServiceDesc for GatewayIPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayIPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GatewayIPC",
	HandlerType: (*GatewayIPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _GatewayIPC_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ipc/gatewayGrpc/gateway.proto",
}
